# Generated by Django 4.2 on 2023-07-18 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("productapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=100, verbose_name="number"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "code",
                    models.CharField(blank=True, max_length=100, verbose_name="code"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("count", models.IntegerField(verbose_name="count")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_products",
                        to="productapp.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Product",
                "verbose_name_plural": "Order Products",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "deliveryType",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        verbose_name="delivery type",
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="payment type"
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=100, verbose_name="status"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="address"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="orders",
                        to="orderapp.orderproduct",
                        verbose_name="order_products",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
