# Generated by Django 4.2 on 2023-07-24 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("productapp", "0002_category_product_available_product_limited_and_more"),
        ("orderapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "basket",
                "verbose_name_plural": "baskets",
            },
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_products",
                to="productapp.product",
                verbose_name="product",
            ),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="basket",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_products",
                to="orderapp.basket",
                verbose_name="basket",
            ),
        ),
    ]
