# Generated by Django 4.2 on 2023-08-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitems",
            name="main",
            field=models.BooleanField(default=False, verbose_name="main category"),
        ),
    ]
