# Generated by Django 4.2 on 2023-07-24 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="src",
            field=models.ImageField(
                default=None, upload_to="media/users/avatars/", verbose_name="url"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.OneToOneField(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="authapp.avatar",
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                unique=True,
                verbose_name="phone number",
            ),
        ),
    ]
