# Generated by Django 4.2 on 2023-07-16 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, verbose_name='full name')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=100, unique=True, verbose_name='phone number')),
                ('avatar', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.avatar', verbose_name='avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
