# Generated by Django 4.2 on 2023-07-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogitem', to='api.image', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Item catalog',
                'verbose_name_plural': 'Item catalogs',
            },
        ),
    ]
