# Generated by Django 4.2 on 2023-07-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_catalogitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogitems', to='api.image', verbose_name='image')),
                ('subcategories', models.ManyToManyField(related_name='catalogitems', to='api.catalogitem', verbose_name='subcategories')),
            ],
            options={
                'verbose_name': 'Item Catalogs',
                'verbose_name_plural': 'Items Catalogs',
            },
        ),
    ]
