# Generated by Django 4.2 on 2023-07-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(max_length=100, verbose_name='category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('count', models.IntegerField(max_length=100, verbose_name='count')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('fullDescription', models.TextField(blank=True, max_length=10000, verbose_name='full description')),
                ('freeDelivery', models.BooleanField(blank=True, default=False, verbose_name='free delivery')),
                ('images', models.ManyToManyField(blank=True, related_name='products', to='api.image', verbose_name='tags')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.review', verbose_name='reviews')),
                ('specifications', models.ManyToManyField(related_name='products', to='api.specification', verbose_name='specifications')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='api.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
