# Generated by Django 4.2 on 2023-07-16 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(verbose_name='count'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('deliveryType', models.CharField(blank=True, max_length=100, verbose_name='delivery type')),
                ('paymentType', models.CharField(blank=True, max_length=100, verbose_name='payment type')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='status')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='address')),
                ('products', models.ManyToManyField(related_name='orders', to='api.product', verbose_name='products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
